# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64)),
                ('helpline_number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='helpercategory',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
    ]
