# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpercategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
