# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('client_number', models.CharField(max_length=16, unique=True)),
                ('status', models.IntegerField(choices=[(1, b'Active'), (2, b'Blocked')], default=1)),
            ],
        ),
    ]
