# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registercall', '0004_auto_20160305_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('action_type', models.IntegerField(choices=[(1, 'General'), (2, 'Specialist'), (3, 'Feedback'), (4, 'Specialist Confirm')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Assign Pending'), (2, 'Assigned'), (3, 'Assigned Timeout'), (4, 'Rejected'), (5, 'Complete Timeout'), (6, 'Completed')], default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='registercall.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Timeout')], default=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='task_manager.Action')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='registercall.Helper')),
            ],
        ),
    ]
