# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registercall', '0001_initial'),
        ('register_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Modified Timestamp')),
                ('action_type', models.IntegerField(choices=[(1, b'Primary'), (2, b'Specialist'), (3, b'Specialist Confirm'), (4, b'Feedback')], default=1)),
                ('status', models.IntegerField(choices=[(1, b'Assign Pending'), (2, b'Assigned'), (3, b'Assigned Timeout'), (4, b'Rejected'), (5, b'Complete Timeout'), (6, b'Completed')], default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='registercall.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Timestamp')),
                ('accepted', models.DateTimeField(auto_now_add=True, verbose_name=b'Accepted Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Modified Timestamp')),
                ('status', models.IntegerField(choices=[(1, b'Pending'), (2, b'Accepted'), (3, b'Rejected'), (4, b'Timeout'), (5, b'Closed'), (6, b'Completed')], default=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='task_manager.Action')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='register_helper.Helper')),
            ],
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('answer', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('feedback_question', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('feedback_answer', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_and_a', to='registercall.Task')),
            ],
        ),
    ]
