# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-30 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name=b'Created Timestamp'),
            preserve_default=False,
        ),
    ]
