# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20160305_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Specialist'), (3, 'Specialist Confirm'), (4, 'Feedback')], default=1),
        ),
    ]
