# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-08 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0001_initial'),
        ('task_manager', '0002_qanda_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], max_length=3)),
                ('status', models.CharField(choices=[(b'pending', b'pending'), (b'completed', b'completed')], max_length=13)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper', to='register_helper.Helper')),
                ('q_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_and_a', to='task_manager.QandA')),
            ],
        ),
    ]
