# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20160315_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 19, 9, 3, 35, 978205, tzinfo=utc), verbose_name='Modified Timestamp'),
            preserve_default=False,
        ),
    ]
