# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_action_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('answer', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('feedback_question', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('feedback_answer', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
