# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_qanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Timeout'), (5, 'Closed'), (6, 'Completed')], default=1),
        ),
    ]
