# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0012_auto_20160324_1435'),
        ('task_manager', '0006_auto_20160325_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='q_and_a', to='registercall.Task'),
            preserve_default=False,
        ),
    ]
