# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_qanda_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='accepted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 4, 14, 25, 20, 182191, tzinfo=utc), verbose_name='Accepted Timestamp'),
            preserve_default=False,
        ),
    ]
