# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_number', models.CharField(blank=True, max_length=16, null=True)),
                ('gcm_canonical_id', models.CharField(max_length=256)),
                ('rating', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Timestamp')),
                ('last_assigned', models.DateTimeField(auto_now_add=True, verbose_name=b'Last Assigned Timestamp')),
                ('status', models.IntegerField(choices=[(1, b'Active'), (2, b'Blocked')], default=1)),
                ('login_status', models.IntegerField(choices=[(1, b'LOGGED_IN'), (2, b'LOGGED_OUT'), (3, b'PENDING')], default=3)),
                ('category', models.ManyToManyField(blank=True, to='management.HelperCategory')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
