# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('helper_number', models.CharField(max_length=16, unique=True)),
                ('gcm_canonical_id', models.CharField(max_length=256)),
                ('rating', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Timestamp')),
                ('last_assigned', models.DateTimeField(auto_now_add=True, verbose_name=b'Last Assigned Timestamp')),
                ('status', models.IntegerField(choices=[(1, b'Active'), (2, b'Blocked')], default=1)),
                ('category', models.ManyToManyField(to='management.HelperCategory')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
            ],
        ),
    ]
