# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160812_2031'),
        ('register_helper', '0002_auto_20160812_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='category',
        ),
        migrations.AddField(
            model_name='helper',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.HelperCategory'),
            preserve_default=False,
        ),
    ]
