# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160812_2031'),
        ('register_helper', '0003_auto_20160812_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='category',
        ),
        migrations.AddField(
            model_name='helper',
            name='category',
            field=models.ManyToManyField(to='management.HelperCategory'),
        ),
    ]
