# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0004_auto_20160812_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='helper_number',
            field=models.CharField(max_length=16),
        ),
    ]
