# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0005_auto_20160812_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='login_status',
            field=models.IntegerField(choices=[(1, b'LOGGED_IN'), (2, b'LOGGED_OUT'), (3, b'PENDING')], default=3),
        ),
    ]
