# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0006_helper_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='helper_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
