# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_helper', '0007_auto_20160816_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='category',
            field=models.ManyToManyField(blank=True, to='management.HelperCategory'),
        ),
    ]
