# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('register_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Timestamp')),
                ('status', models.IntegerField(choices=[(1, b'Created'), (2, b'Blocked'), (3, b'Merged')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='register_client.Client')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='management.HelpLine')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Modified Timestamp')),
                ('status', models.IntegerField(choices=[(1, b'Pending'), (2, b'Completed'), (3, b'Rejected')], default=1)),
                ('call_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='registercall.CallRequest')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management.HelperCategory')),
            ],
        ),
    ]
