# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Blocked'), (3, 'Merged')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('client_number', models.CharField(max_length=16, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Blocked')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('helper_number', models.CharField(max_length=16, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Blocked')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64)),
                ('helpline_number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('category', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1)),
                ('call_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='registercall.CallRequest')),
            ],
        ),
        migrations.AddField(
            model_name='callrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='registercall.Client'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='registercall.HelpLine'),
        ),
    ]
