# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
