# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0003_auto_20160301_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Rejected')], default=1),
        ),
    ]
