# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0005_helper_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
    ]
