# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0006_auto_20160305_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='helper',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='helper',
            name='category',
            field=models.ManyToManyField(default='General', to='registercall.HelperCategory'),
        ),
    ]
