# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0008_auto_20160311_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='gcm_authorization_key',
            field=models.CharField(default='bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1', max_length=64),
            preserve_default=False,
        ),
    ]
