# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0009_helper_gcm_authorization_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='gcm_authorization_key',
            new_name='gcm_canonical_id',
        ),
    ]
