# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0010_auto_20160315_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='gcm_canonical_id',
            field=models.CharField(max_length=256),
        ),
    ]
