# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0011_auto_20160318_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='registercall.HelperCategory'),
        ),
    ]
