# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 05:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0012_auto_20160324_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='last_assigned',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 3, 5, 11, 27, 575237, tzinfo=utc), verbose_name='Last Assigned Timestamp'),
            preserve_default=False,
        ),
    ]
