# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_auto_20160812_1601'),
        ('registercall', '0013_helper_last_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='category',
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='management.HelpLine'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management.HelperCategory'),
        ),
        migrations.DeleteModel(
            name='Helper',
        ),
        migrations.DeleteModel(
            name='HelperCategory',
        ),
        migrations.DeleteModel(
            name='HelpLine',
        ),
    ]
