# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('registercall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_no', models.CharField(max_length=15)),
                ('caller_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='ivr_audio/')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
            ],
        ),
        migrations.CreateModel(
            name='IVR_Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='ivr_audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelperCategory')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
            ],
        ),
        migrations.CreateModel(
            name='IVR_Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=256)),
                ('caller_no', models.CharField(max_length=15)),
                ('caller_location', models.CharField(max_length=256)),
                ('helpline_no', models.CharField(max_length=15)),
                ('language_option', models.CharField(max_length=2)),
                ('category_option', models.CharField(max_length=2)),
                ('session_next', models.CharField(choices=[(0, b'welcome'), (1, b'display_language'), (2, b'get_language'), (3, b'display_option'), (4, b'get_option'), (5, b'display_terms'), (6, b'get_terms'), (7, b'call_exit'), (8, b'call_forward')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
            ],
        ),
        migrations.CreateModel(
            name='Misc_Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='ivr_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Misc_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='misc_audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Misc_Category'),
        ),
        migrations.AddField(
            model_name='misc_audio',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
        migrations.AddField(
            model_name='misc_audio',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Language'),
        ),
        migrations.AddField(
            model_name='ivr_audio',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Language'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='feedbackType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.FeedbackType'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackresponses',
            field=models.ManyToManyField(to='ivr.FeedbackResponse'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registercall.Task'),
        ),
    ]
