# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IVR_Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=256)),
                ('caller_no', models.CharField(max_length=15)),
                ('caller_location', models.CharField(max_length=256)),
                ('helpline_no', models.CharField(max_length=15)),
                ('category_option', models.CharField(max_length=2)),
                ('session_next', models.CharField(max_length=256)),
            ],
        ),
    ]
