# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr_call',
            name='session_next',
            field=models.CharField(choices=[(1, b'display_option'), (2, b'get_option')], max_length=256),
        ),
    ]
