# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0002_auto_20160820_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_no', models.CharField(max_length=15)),
                ('caller_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='ivr_call',
            name='session_next',
            field=models.CharField(choices=[(0, b'welcome'), (1, b'display_option'), (2, b'get_option'), (3, b'call_exit')], max_length=256),
        ),
    ]
