# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-03 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0002_auto_20170330_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Forward_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_no', models.CharField(max_length=15)),
                ('caller_no', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('completed', 'completed')], default='initiated', max_length=15)),
            ],
        ),
    ]
