# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-24 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0003_call_forward_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackresponses',
            field=models.ManyToManyField(blank=True, null=True, to='ivr.FeedbackResponse'),
        ),
    ]
