# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160812_2031'),
        ('ivr', '0004_auto_20170105_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc_Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='ivr_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='misc_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine')),
            ],
        ),
        migrations.AddField(
            model_name='misc_audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.misc_category'),
        ),
        migrations.AddField(
            model_name='misc_audio',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
        ),
    ]
