# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registercall', '0001_initial'),
        ('ivr', '0006_call_forward_details_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_forward',
            name='task',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='registercall.Task'),
        ),
    ]
