# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0009_auto_20170519_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_forward_details',
            name='call_duration',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='call_forward_details',
            name='call_pickup_duration',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='call_forward_details',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('not_answered', 'not_answered'), ('completed', 'completed')], default='initiated', max_length=15),
        ),
    ]
