# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0014_auto_20170105_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ivr_call',
            name='session_next',
            field=models.CharField(choices=[(0, b'welcome'), (1, b'display_language'), (2, b'get_language'), (3, b'display_option'), (4, b'get_option'), (5, b'call_exit'), (6, b'call_forward')], max_length=256),
        ),
        migrations.AlterField(
            model_name='misc_audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Misc_Category'),
        ),
    ]
