# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160812_2031'),
        ('ivr', '0017_auto_20170106_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
        migrations.AddField(
            model_name='language',
            name='helpline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.HelpLine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='misc_audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Misc_Category'),
        ),
    ]
