# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0018_auto_20170106_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivr_call',
            name='language_option',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='misc_audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.Misc_Category'),
        ),
    ]
